language: python

python:
    - "2.7"

before_install:
    - export CHARON_BASE_URL="http://tracking.database.org"
    - export CHARON_API_TOKEN="charonapitokengoeshere"
    - mkdir /home/travis/.ngipipeline
    - "echo foo: bar > /home/travis/.ngipipeline/ngi_config.yaml"
    - pip install setuptools --upgrade
    - pip install pyexcel==0.5.15
    - pip install pyexcel-xlsx==0.5.8
    - pip install git+https://github.com/SciLifeLab/flowcell_parser.git@master
    - pip install git+https://github.com/SciLifeLab/TACA.git@master
    - pip install codecov

install:
    - python setup.py install

script:
    - cd tests && nosetests --with-coverage -v -s

after_success:
    - codecov

notifications:
    email: false
